# Generated by Django 3.0 on 2019-12-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('link', models.URLField(max_length=2083)),
                ('vegetarian', models.BooleanField()),
                ('cook_time', models.IntegerField()),
            ],
        ),
    ]
