# Generated by Django 3.0 on 2019-12-20 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=200)),
                ('link', models.URLField(blank=True, max_length=2083)),
                ('image_link', models.URLField(blank=True, max_length=2083)),
                ('genres', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=200)),
                ('cook_time', models.IntegerField()),
                ('prep_time', models.IntegerField()),
                ('freezes_well', models.BooleanField(default=False)),
                ('vegetarian', models.BooleanField(default=False)),
                ('could_be_vegetarian', models.BooleanField(default=False)),
                ('spicy', models.BooleanField(default=False)),
                ('could_be_spicy', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('times_made', models.IntegerField(default=0)),
                ('last_time_made', models.DateField(blank=True)),
            ],
        ),
    ]
