# Generated by Django 3.0 on 2019-12-21 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='genres',
        ),
        migrations.AddField(
            model_name='recipe',
            name='genres',
            field=models.ManyToManyField(to='recipes.Genre'),
        ),
    ]
