# Generated by Django 3.0 on 2019-12-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_time_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
