# Generated by Django 3.0 on 2019-12-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20191221_0439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='last_time_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
