# Generated by Django 3.0 on 2019-12-21 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191221_0445'),
        ('recipes', '0002_auto_20191220_0514'),
    ]

    operations = [
    ]
