# Generated by Django 3.0 on 2019-12-23 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_merge_20191221_1829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='food_name',
            new_name='name',
        ),
    ]
